'use client';
import { useParams, useRouter } from 'next/navigation';
import { useQuery, useMutation } from '@tanstack/react-query';
import { api } from '@/lib/api';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { ScoreRing, SectionBar } from '@/components/score-ring';
import { Sparkles } from 'lucide-react';

const LABELS: Record<string, string> = {
  hard_skill: 'Hard-skill coverage',
  nice_to_have: 'Nice-to-have coverage',
  keyword: 'Keyword density & placement',
  semantic: 'Semantic similarity',
  experience: 'Experience relevance',
  education: 'Education / certifications',
  formatting: 'ATS formatting compliance',
  readability: 'Recruiter readability',
};

export default function ScorePage() {
  const { id } = useParams<{ id: string }>();
  const router = useRouter();
  const q = useQuery({ queryKey: ['score', id], queryFn: () => api.getScore(id) });
  const optimize = useMutation({
    mutationFn: () => api.runOptimize(q.data.resumeVersionId, q.data.jdId),
    onSuccess: (r) => router.push(`/optimize/${r.newVersionId}`),
  });

  if (q.isLoading || !q.data) return <div className="p-8">Loading score…</div>;
  const s = q.data;

  return (
    <div className="max-w-6xl mx-auto p-8 space-y-6">
      <header>
        <h1 className="text-2xl font-semibold tracking-tight">ATS score</h1>
        <p className="text-muted-fg">
          {s.jd?.title} {s.jd?.company ? `· ${s.jd.company}` : ''}
        </p>
      </header>

      <div className="grid md:grid-cols-[200px_1fr] gap-8 items-start">
        <Card>
          <CardContent className="grid place-items-center p-6">
            <ScoreRing score={s.overall} />
            <div className="mt-2 text-sm text-muted-fg">Recruiter fit: <span className="text-fg font-medium">{Math.round(s.recruiterFit)}</span></div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Sub-scores</CardTitle>
            <CardDescription>Weighted contributions to the overall score.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            {Object.entries(s.sectionScores || {}).map(([k, v]) => (
              <SectionBar key={k} label={LABELS[k] || k} value={Number(v)} />
            ))}
          </CardContent>
        </Card>
      </div>

      <div className="grid md:grid-cols-2 gap-4">
        <Card>
          <CardHeader>
            <CardTitle>Matched must-have skills</CardTitle>
            <CardDescription>{(s.matchedSkills || []).length} of {(s.matchedSkills || []).length + (s.missingSkills || []).length} requirements</CardDescription>
          </CardHeader>
          <CardContent className="flex flex-wrap gap-2">
            {(s.matchedSkills || []).map((sk: string) => <Badge key={sk} variant="success">{sk}</Badge>)}
            {!(s.matchedSkills || []).length && <p className="text-muted-fg text-sm">None yet.</p>}
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Missing must-have skills</CardTitle>
            <CardDescription>Add these if you truly have them.</CardDescription>
          </CardHeader>
          <CardContent className="flex flex-wrap gap-2">
            {(s.missingSkills || []).map((sk: string) => <Badge key={sk} variant="danger">{sk}</Badge>)}
            {!(s.missingSkills || []).length && <p className="text-muted-fg text-sm">All covered.</p>}
          </CardContent>
        </Card>
        <Card className="md:col-span-2">
          <CardHeader>
            <CardTitle>Missing keywords</CardTitle>
            <CardDescription>Phrases from the JD not detected in your resume.</CardDescription>
          </CardHeader>
          <CardContent className="flex flex-wrap gap-2">
            {(s.missingKeywords || []).map((k: string) => <Badge key={k} variant="warning">{k}</Badge>)}
            {!(s.missingKeywords || []).length && <p className="text-muted-fg text-sm">No major keyword gaps.</p>}
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Improvement plan</CardTitle>
          <CardDescription>Generated by Claude based on the score breakdown.</CardDescription>
        </CardHeader>
        <CardContent>
          <article className="prose prose-sm dark:prose-invert max-w-none whitespace-pre-wrap">
            {s.rationale}
          </article>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2"><Sparkles size={18} /> Optimize for this JD</CardTitle>
          <CardDescription>
            Rewrites your Summary and top bullets to align with this JD's must-haves.
            Truth-checked: no fabricated companies, dates, or numbers. Old vs new score is shown side-by-side.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-2">
          <Button disabled={optimize.isPending} onClick={() => optimize.mutate()}>
            {optimize.isPending ? 'Optimizing… (15–60s)' : 'Optimize resume'}
          </Button>
          {optimize.isError && (
            <p className="text-sm text-danger">{(optimize.error as any)?.message}</p>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
